[package]
name = "zero_to_hello_rust"
version = "0.1.0"
authors = ["damour <tuyishimejeand88@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "zero_to_hello_rust"
path = "src/main.rs"
